name: GitHub Actions Demo
on:
  push:
    branches:
      - main
jobs:
  Blogs-to-Gists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: pip install pygithub
      - uses: dorny/paths-filter@v2
        id: blog
        with:
          list-files: shell
          filters: |
            create_blog:
            - added: 'blog/**.md'
            update_blog:
            - modified: 'blog/**.md'
      # Run only if files in './blog' were added or changed
      - if: steps.blog.outputs.create_blog == 'true'
        env:
          GISTS_TOKEN: ${{ secrets.GISTS_TOKEN }}
        run: python gistblog.py create "${{ steps.blog.outputs.create_blog_files }}"
      - if: steps.blog.outputs.create_blog == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Adds new blog posts from GitHub Actions
      - if: steps.blog.outputs.update_blog == 'true'
        env:
          GISTS_TOKEN: ${{ secrets.GISTS_TOKEN }}
        run: python gistblog.py update "${{ steps.blog.outputs.update_blog_files }}"
