name: GitHub Actions Demo
on: [push]
#  push:
#    branches:
#      - main
jobs:
  Blogs-to-Gists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: shell
          filters: |
            blog:
            - 'blog/**'
            
      # Run only if files in './blog' were added or changed
      - name: Run blog_to_gists.py
        if: steps.filter.outputs.backend == 'true'
        run: python blogs_to_gists.py ${{ steps.filter.outputs.blog_files }}
