name: GitHub Actions Demo
on: [push]
#  push:
#    branches:
#      - main
jobs:
  Blogs-to-Gists:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: shell
          filters: |
            blog:
              - 'blog/**'
            
      # Run only if files in './blog' were added or changed
      - if: ${{ steps.filter.outputs.blog == 'true' }}
        run: python3 blogs_to_gists.py ${{ steps.filter.outputs.blog_files }}
