name: GitHub Actions Demo
on: [push]
#  push:
#    branches:
#      - main
jobs:
  Blogs-to-Gists:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: python3 blogs_to_gists.py
