name: GitHub Actions Demo
on: [push]
#  push:
#    branches:
#      - main
jobs:
  Blogs-to-Gists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: dorny/paths-filter@v2
        id: blog
        with:
          list-files: shell
          filters: |
            create:
            - added: 'blog/**'
            update:
            - modified: 'blog/**'
            
      # Run only if files in './blog' were added or changed
      - if: steps.blog.outputs.create == 'true'
        run: python blog_to_gists.py create ${{ steps.blog.outputs.blog_files }}
      - if: steps.blog.outputs.update == 'true'
        run: python blog_to_gists.py update ${{ steps.blog.outputs.blog_files }}
